#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest import Filter
from runtest_openrsp import OpenRSPTestRun

test_run = OpenRSPTestRun(__file__, sys.argv)

f_out = Filter()
f_out.add(from_string = 'Final results from SIRIUS',
          num_lines   = 11,
          tolerance   = 1.0e-7)

f_stdout = Filter()
f_stdout.add(from_string  = 'beta = -Efff',
             num_lines    = 10,
             tolerance    = 1.0e-7,
             ignore_below = 1.0e-7)

test_run.execute(['hf.dal', 'hf_2np1.dal'], ['h2o2.mol'], {'out': f_out, 'stdout': f_stdout})

sys.exit(0)
