#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from beholder import Filter
from beholder_openrsp import OpenRSPTestRun

test_run = OpenRSPTestRun(__file__, sys.argv)

f = Filter()
f.add(ignore_below=1.0e-3) # all lines

test_run.execute(['ff_b3lyp.dal', 'fff_b3lyp.dal', 'ffff_b3lyp.dal', 'fffff_b3lyp.dal'], ['aug-dz.mol'],
                 {'rsp_tensor_human': f}, args='-get rsp_tensor_human')

sys.exit(0)
