#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from beholder import Filter
from beholder_openrsp import OpenRSPTestRun

test_run = OpenRSPTestRun(__file__, sys.argv)

f_out = Filter()
f_out.add(from_string  = 'Final results from SIRIUS',
          num_lines    = 11,
          tolerance    = 1.0e-7)
f_out.add(from_string  = 'RSPC Calling print_shypol',
          to_string    = 'RSPC Backing from vib_ana_polari',
          tolerance    = 1.0e-5,
          ignore_below = 1.0e-9)

f_stdout = Filter()
f_stdout.add(from_string = 'dipmom = -Ef',
             num_lines   = 2,
             tolerance   = 1.0e-6)
f_stdout.add(from_string = 'Alpha = -Eff w:  -0.072   0.072',
             num_lines   = 4,
             tolerance   = 1.0e-6)
f_stdout.add(from_string = 'd/dg Alpha = -Egff w:   0.000  -0.072   0.072',
             num_lines   = 10,
             tolerance   = 1.0e-6)
f_stdout.add(from_string = 'Gamma = -Effff w:  -0.072   0.072  -0.072   0.072',
             num_lines   = 28,
             tolerance   = 1.0e-5)

test_run.execute(['cars.dal'], ['h2o2.mol'], {'out': f_out, 'stdout': f_stdout}, args='-put DALTON.HES')

sys.exit(0)
