#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest import Filter
from runtest_openrsp import OpenRSPTestRun

test_run = OpenRSPTestRun(__file__, sys.argv)

f = Filter()
f.add(from_string = 'AAT',
      num_lines   = 4,
      tolerance   = 1.0e-9)

test_run.execute(['vcd.dal'], ['h2o2.mol'], {'stdout': f})

sys.exit(0)
