#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest import Filter
from runtest_openrsp import OpenRSPTestRun

test_run = OpenRSPTestRun(__file__, sys.argv)

f = Filter()
f.add(from_string  = 'no-London Magnetizability = Eoo',
      num_lines    = 4,
      tolerance    = 1.0e-5,
      ignore_below = 1.0e-9)
f.add(from_string  = 'London Magnetizability = Ebb',
      num_lines    = 4,
      tolerance    = 1.0e-5,
      ignore_below = 1.0e-9)

test_run.execute(['hf.dal'], ['h2o2.mol', 'fh.mol'], {'stdout': f})

sys.exit(0)
