#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest import Filter
from runtest_openrsp import OpenRSPTestRun

test_run = OpenRSPTestRun(__file__, sys.argv)

f = Filter()
f.add() # all lines

test_run.execute(['pe_beta1.dal','pe_beta2.dal'], ['sto_3g.mol'],
                 {'rsp_tensor_human': f}, args='-pot 2_h2o.pot -get rsp_tensor_human')

sys.exit(0)
