#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(rel_tolerance = 1.0e-4) # all lines

for method in ['hf', 'lda', 'b3lyp']:
    for prop in ['ggg']:
        test.run(['%s_%s.dal' % (prop, method)], ['mol.mol'],
                 {'rsp_tensor_human': f}, args='-get rsp_tensor_human')

sys.exit(test.return_code)
