#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()
f.add(from_string  = 'd/db G-prime-noL',
      num_lines    = 10,
      rel_tolerance    = 1.0e-6,
      ignore_below = 1.0e-9)
f.add(from_string  = 'd/db A-tensor-noL',
      num_lines    = 10,
      rel_tolerance    = 1.0e-6,
      ignore_below = 1.0e-9)
f.add(from_string  = 'd/df d/db G-prime-noL',
      num_lines    = 28,
      rel_tolerance    = 1.0e-6,
      ignore_below = 1.0e-9)
f.add(from_string  = 'd/df d/db A-tensor-noL',
      num_lines    = 28,
      rel_tolerance    = 1.0e-6,
      ignore_below = 1.0e-9)
f.add(from_string  = 'd/db G-prime-Lon',
      num_lines    = 10,
      rel_tolerance    = 1.0e-6,
      ignore_below = 1.0e-9)
f.add(from_string  = 'd/db A-tensor-Lon',
      num_lines    = 10,
      rel_tolerance    = 1.0e-6,
      ignore_below = 1.0e-9)
f.add(from_string  = 'd/df d/db G-prime-Lon',
      num_lines    = 28,
      rel_tolerance    = 1.0e-6,
      ignore_below = 1.0e-9)
f.add(from_string  = 'd/df d/db A-tensor-Lon',
      num_lines    = 28,
      rel_tolerance    = 1.0e-6,
      ignore_below = 1.0e-9)

test.run(['jones.dal'], ['h2o2.mol'], {'stdout': f})

sys.exit(test.return_code)
