#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from beholder import Filter
from beholder_openrsp import OpenRSPTestRun

test_run = OpenRSPTestRun(__file__, sys.argv)

f = Filter()
f.add(from_string  = 'd/db G-prime-noL',
      num_lines    = 10,
      tolerance    = 1.0e-6,
      ignore_below = 1.0e-9)
f.add(from_string  = 'd/db A-tensor-noL',
      num_lines    = 10,
      tolerance    = 1.0e-6,
      ignore_below = 1.0e-9)
f.add(from_string  = 'd/df d/db G-prime-noL',
      num_lines    = 28,
      tolerance    = 1.0e-6,
      ignore_below = 1.0e-9)
f.add(from_string  = 'd/df d/db A-tensor-noL',
      num_lines    = 28,
      tolerance    = 1.0e-6,
      ignore_below = 1.0e-9)
f.add(from_string  = 'd/db G-prime-Lon',
      num_lines    = 10,
      tolerance    = 1.0e-6,
      ignore_below = 1.0e-9)
f.add(from_string  = 'd/db A-tensor-Lon',
      num_lines    = 10,
      tolerance    = 1.0e-6,
      ignore_below = 1.0e-9)
f.add(from_string  = 'd/df d/db G-prime-Lon',
      num_lines    = 28,
      tolerance    = 1.0e-6,
      ignore_below = 1.0e-9)
f.add(from_string  = 'd/df d/db A-tensor-Lon',
      num_lines    = 28,
      tolerance    = 1.0e-6,
      ignore_below = 1.0e-9)

test_run.execute(['jones.dal'], ['h2o2.mol'], {'stdout': f})

sys.exit(0)
