#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from runtest_dalton import Filter, TestRun

test = TestRun(__file__, sys.argv)

f_out = Filter()
f_out.add(from_string = 'Final results from SIRIUS',
          num_lines   = 11,
          tolerance   = 1.0e-7)

f_stdout = Filter()
f_stdout.add(from_string = 'alpha = -Eff',
             num_lines   = 4,
             tolerance   = 1.0e-4)

test.run(['hf.dal'], ['h2o2.mol'], {'out': f_out, 'stdout': f_stdout})

sys.exit(test.return_code)
