#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from beholder import Filter
from beholder_openrsp import OpenRSPTestRun

test_run = OpenRSPTestRun(__file__, sys.argv)

f = Filter()
f.add(tolerance = 1.0e-4) # all lines

for method in ['hf', 'lda', 'b3lyp']:
    for prop in ['g', 'gg', 'ggg', 'gggg']:
        test_run.execute(['%s_%s.dal' % (prop, method)], ['mol.mol'],
                         {'rsp_tensor_human': f}, args='-get rsp_tensor_human')

sys.exit(0)
