#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from beholder import Filter
from beholder_openrsp import OpenRSPTestRun

test_run = OpenRSPTestRun(__file__, sys.argv)

f_out = Filter()
f_out.add(from_string  = 'Raman related properties for freq',
          to_string    = '   **** For definitions, see the DALTON manual and references therein. ****')
f_out.add(from_string  = 'RSPC Calling print_shypol',
          to_string    = 'RSPC Backing from vib_ana_polari',
          tolerance    = 1.0e-5,
          ignore_below = 1.0e-9)

f_stdout = Filter()
f_stdout.add(from_string = 'd/dg Polari = -Egff',
             nr_lines    = 10,
             tolerance   = 1.0e-6)
f_stdout.add(from_string = 'd/dg G-prime = Egbf',
             nr_lines    = 10,
             tolerance   = 1.0e-6)
f_stdout.add(from_string = 'd/dg A-tensor = -Egqf',
             nr_lines    = 19,
             tolerance   = 1.0e-6)

test_run.execute(['roa.dal'], ['h2o2.mol'], {'out': f_out, 'stdout': f_stdout}, args='-put DALTON.HES')

sys.exit(0)
