      LOGICAL SKIP, EXPJAC, LRTEST, NEWRD, NOTRIA, NOSOL, RDTEST, CUT
      COMMON /CBICZR/ DTEST, THRESH,
     &                SKIP, IPRINT, MAXSIM, EXPJAC, LRTEST,
     &                NEWRD, NOTRIA, MAXIT, NOSOL, RDTEST, CUT
