      LOGICAL SKIP, EXPJAC, LRTEST, NEWRD, NOTRIA, NOSOL, RDTEST, CUT
      COMMON /CBICTR/ THRESH, DTEST,
     &                SKIP, IPRINT, MAXSIM, EXPJAC, LRTEST,
     &                NEWRD, NOTRIA, MAXIT, NOSOL, RDTEST, CUT
