      LOGICAL  RUNTWO, RTNTWO, TKTIME, SOFOCK, USRSCR
      COMMON /CBIHR2/ RUNTWO, IPRTWO, IPRNTA, IPRNTB, IPRNTC, IPRNTD,
     &                THRTWO, RTNTWO, TKTIME, ICEDIF, IFTHRS, SOFOCK,
     &                USRSCR
      COMMON /CBRHR2/ THRFAC(2)
