C
C cbirhs.h  1998/08/11 
C
      LOGICAL SKIP, RUNINT,
     &        RUNFCK, TWOH1, NOH1, NOH2, FCKTST, RUNSDR, RUNTRA,
     &        SDRTST, UNDIF, TRATST, RUNGDY, NODC, NODV, NOPV, TESTFS,
     &        DIAGTD, NOFD , NOFS, NOSSF, NOORTH, GDHAM, RETUR, TKTIME,
     &        AOMAT, CUT, DMAGGD(3), NODDY, NODPTR, RUNPTR, RALLCO
      COMMON /CBIRHS/ SKIP, RUNINT, RUNFCK, IPRALL, IPRFD, IPRINT,
     &                IPRNTA, IPRNTB, IPRNTC, IPRNTD, IPRMAX, MAXSIM,
     &                TWOH1, NOH1, NOH2, FCKTST, RUNSDR, RUNTRA,
     &                IPRSDR, IPRTRA, SDRTST, UNDIF, TRATST, RUNGDY,
     &                IPRGDY, NODC, NODV, NOPV, TESTFS, DIAGTD, NOFD,
     &                NOFS, NOSSF, NOORTH, GDHAM, RETUR, TKTIME,
     &                AOMAT, CUT, DMAGGD, NODDY, NODPTR, IPRPTR, IPRSOR,
     &                RUNPTR, RALLCO, IPRIN4, IPRIN6 
