      LOGICAL SKIP, NOTRIA, NEWRD, RSTNR, NOAVER, D1DIAG, PRIL2, CUT
      COMMON /CBIRES/ THRRNR, MAXRNR, KAPTST,
     *                IPRINT, MAXSIM, IRDC, NRDC, NRDT, NRDCO(MXCOOR),
     *                SKIP, NOTRIA, NEWRD, RSTNR, NOAVER,
     *                D1DIAG, PRIL2, CUT, MAXRED
