      LOGICAL         COMPAR, SKIP, NOROT1,
     *                HESTRO, GDTRO, RDTRO, TROGRD, TROHES, TRODIP, CUT
      COMMON /CBITRO/ THRESH, IPRINT, COMPAR, SKIP, NOROT1,
     *                HESTRO, GDTRO, RDTRO, TROGRD, TROHES, TRODIP, CUT
