      INTEGER MX4ROP, MX4RFR
      PARAMETER ( MX4ROP = 256, MX4RFR = 60)

      LOGICAL L_USE_CHI3

      INTEGER IPR4HYP, N4RFREQ, N4ROPER

      INTEGER IA4ROP, IB4ROP, IC4ROP, ID4ROP, IE4ROP

#if defined (SYS_CRAY)
      REAL A4RFR, B4RFR, C4RFR, D4RFR, E4RFR
#else
      DOUBLE PRECISION A4RFR, B4RFR, C4RFR, D4RFR, E4RFR
#endif
      COMMON /INF4HYP/ A4RFR(MX4RFR), B4RFR(MX4RFR), 
     *                 C4RFR(MX4RFR), D4RFR(MX4RFR), E4RFR(MX4RFR),
     *                 IA4ROP(MX4ROP), IB4ROP(MX4ROP), 
     *                 IC4ROP(MX4ROP), ID4ROP(MX4ROP), IE4ROP(MX4ROP),
     *                 N4RFREQ, IPR4HYP, N4ROPER, L_USE_CHI3

