      INTEGER MX5ROP, MX5RFR
      PARAMETER ( MX5ROP = 750, MX5RFR = 60)

      INTEGER IPR5HYP, N5RFREQ, N5ROPER

      INTEGER I5ROP(MX5ROP,6)

#if defined (SYS_CRAY)
      REAL FREQ5(MX5RFR,6)
#else
      DOUBLE PRECISION FREQ5(MX5RFR,6)
#endif
      COMMON /INF5HYP/ FREQ5, I5ROP, N5RFREQ, IPR5HYP, N5ROPER

