      INTEGER MAXCLBL
      PARAMETER ( MAXCLBL = 60 )
      INTEGER NLRCLBL,ISYLRC,ISYOFC,ILRCAU
      CHARACTER*8 LRCLBL

      COMMON/ILRCRSP/ NLRCLBL,ISYLRC(MAXCLBL),ISYOFC(8),ILRCAU(MAXCLBL)
      COMMON/CLRCRSP/ LRCLBL(MAXCLBL)
