      INTEGER MAXCL2LBL
      PARAMETER ( MAXCL2LBL = 360 )

      LOGICAL LCL2OPN

      INTEGER NCL2LBL, ISYOFCL2(8)

      INTEGER ISYCL2(MAXCL2LBL,2)

      INTEGER ICL2CAU(MAXCL2LBL,2)

      CHARACTER*8 LBLCL2(MAXCL2LBL,2)

      COMMON/ICL2RSP/ ISYCL2, NCL2LBL, ICL2CAU, ISYOFCL2, LCL2OPN
      COMMON/CCL2RSP/ LBLCL2
