      INTEGER MAXCO2LBL
      PARAMETER ( MAXCO2LBL = 360 )

      LOGICAL LCO2OPN

      INTEGER NCO2LBL, ISYOFCO2(8)

      INTEGER ISYCO2(MAXCO2LBL,2)

      INTEGER ICO2CAU(MAXCO2LBL,2)

      CHARACTER*8 LBLCO2(MAXCO2LBL,2)

      COMMON/ICO2RSP/ ISYCO2, NCO2LBL, ICO2CAU, ISYOFCO2, LCO2OPN
      COMMON/CCO2RSP/ LBLCO2
