      INTEGER MXCROP, MXCRFR, MXCRDISP
      PARAMETER ( MXCROP = 240, MXCRFR = 60, MXCRDISP = 581)

      INTEGER IPRCHYP, NCRFREQ, NCROPER, NCRDISP, NCRDSPE, NCRDSPO

      INTEGER IACROP(MXCROP), IBCROP(MXCROP)
      INTEGER ICCROP(MXCROP), IDCROP(MXCROP)
      INTEGER ICROP(MXCROP,4)
      EQUIVALENCE ( IACROP(1), ICROP(1,1) )
      EQUIVALENCE ( IBCROP(1), ICROP(1,2) )
      EQUIVALENCE ( ICCROP(1), ICROP(1,3) )
      EQUIVALENCE ( IDCROP(1), ICROP(1,4) )

      INTEGER ICCAUA(MXCRDISP), ICCAUB(MXCRDISP)
      INTEGER ICCAUC(MXCRDISP), ICCAUD(MXCRDISP)
      INTEGER ICCAU(MXCRDISP,4)
      EQUIVALENCE ( ICCAUA(1), ICCAU(1,1) )
      EQUIVALENCE ( ICCAUB(1), ICCAU(1,2) )
      EQUIVALENCE ( ICCAUC(1), ICCAU(1,3) )
      EQUIVALENCE ( ICCAUD(1), ICCAU(1,4) )

      LOGICAL L_USE_CHI2, L_USE_XKS3, NO_2NP1_RULE
      LOGICAL USE_LBCD, USE_L2BC
      LOGICAL GAMMA_PAR, GAMMA_ORT

      CHARACTER*(8) CSYM

#if defined (SYS_CRAY)
      REAL ACRFR(MXCRFR), BCRFR(MXCRFR)
      REAL CCRFR(MXCRFR), DCRFR(MXCRFR)
      REAL CRFR(MXCRFR,4)
#else
      DOUBLE PRECISION ACRFR(MXCRFR), BCRFR(MXCRFR)
      DOUBLE PRECISION CCRFR(MXCRFR), DCRFR(MXCRFR)
      DOUBLE PRECISION CRFR(MXCRFR,4)
#endif
      EQUIVALENCE ( ACRFR(1), CRFR(1,1) )
      EQUIVALENCE ( BCRFR(1), CRFR(1,2) )
      EQUIVALENCE ( CCRFR(1), CRFR(1,3) )
      EQUIVALENCE ( DCRFR(1), CRFR(1,4) )

      COMMON /INFCHYP/ CRFR, ICROP, ICCAU,
     *                 NCRFREQ, IPRCHYP, NCROPER, 
     *                 NCRDISP, NCRDSPE, NCRDSPO,
     *                 L_USE_CHI2, L_USE_XKS3, NO_2NP1_RULE,
     *                 USE_LBCD, USE_L2BC,
     *                 GAMMA_PAR, GAMMA_ORT, CSYM

