      INTEGER MAXCR2LBL
      PARAMETER ( MAXCR2LBL = 360 )

      LOGICAL LCR2OPN

      INTEGER NCR2LBL, ISYOFCR2(8)

      INTEGER ISYCR2(MAXCR2LBL,2)

      INTEGER ICR2CAU(MAXCR2LBL,2)

      CHARACTER*8 LBLCR2(MAXCR2LBL,2)

      COMMON/ICR2RSP/ ISYCR2, NCR2LBL, ICR2CAU, ISYOFCR2, LCR2OPN
      COMMON/CCR2RSP/ LBLCR2
