      INTEGER MAXCX2LBL
      PARAMETER ( MAXCX2LBL = 360 )

      LOGICAL LCX2OPN

      INTEGER NCX2LBL, ISYOFCX2(8)

      INTEGER ISYCX2(MAXCX2LBL,2)

      INTEGER ICX2CAU(MAXCX2LBL,2)

      CHARACTER*8 LBLCX2(MAXCX2LBL,2)

      COMMON/ICX2RSP/ ISYCX2, NCX2LBL, ICX2CAU, ISYOFCX2, LCX2OPN
      COMMON/CCX2RSP/ LBLCX2
