      INTEGER MAXEL1LBL
      PARAMETER ( MAXEL1LBL = 60 )

      LOGICAL LEL1OPN
      INTEGER NEL1LBL, ISYOFEL1

      INTEGER ISTEL1(MAXEL1LBL)

      INTEGER ISYSEL1(MAXEL1LBL)
      INTEGER ISYOEL1(MAXEL1LBL)

      LOGICAL LPREL1(MAXEL1LBL)
      LOGICAL LORXEL1(MAXEL1LBL) 

      CHARACTER*8 LBLEL1(MAXEL1LBL)

#if defined (SYS_CRAY)
      REAL EIGEL1(MAXEL1LBL)
      REAL FRQEL1(MAXEL1LBL)
#else
      DOUBLE PRECISION EIGEL1(MAXEL1LBL)
      DOUBLE PRECISION FRQEL1(MAXEL1LBL)
#endif

      COMMON/IEL1RSP/ ISTEL1, ISYSEL1, ISYOEL1, LPREL1, LORXEL1,
     &                NEL1LBL, ISYOFEL1(8), LEL1OPN
      COMMON/CEL1RSP/ LBLEL1
      COMMON/REL1RSP/ EIGEL1, FRQEL1

