      INTEGER MAXER1LBL
      PARAMETER ( MAXER1LBL = 60 )

      LOGICAL LER1OPN
      INTEGER NER1LBL, ISYOFER1

      INTEGER ISTER1(MAXER1LBL)

      INTEGER ISYSER1(MAXER1LBL)
      INTEGER ISYOER1(MAXER1LBL)

      LOGICAL LPRER1(MAXER1LBL)
      LOGICAL LORXER1(MAXER1LBL)

      CHARACTER*8 LBLER1(MAXER1LBL)

#if defined (SYS_CRAY)
      REAL EIGER1(MAXER1LBL)
      REAL FRQER1(MAXER1LBL)
#else
      DOUBLE PRECISION EIGER1(MAXER1LBL)
      DOUBLE PRECISION FRQER1(MAXER1LBL)
#endif

      COMMON/IER1RSP/ ISTER1, ISYSER1, ISYOER1, LPRER1, LORXER1,
     &                NER1LBL, ISYOFER1(8), LER1OPN
      COMMON/CER1RSP/ LBLER1
      COMMON/RER1RSP/ EIGER1, FRQER1

