      INTEGER MAXER2LBL
      PARAMETER ( MAXER2LBL = 20 )

      LOGICAL LER2OPN
      INTEGER NER2LBL, ISYOFER2

      INTEGER ISTER2(MAXER2LBL)

      INTEGER ISYSER2(MAXER2LBL)
      INTEGER ISYOER2(MAXER2LBL,2)
  
      LOGICAL LPRER2(MAXER2LBL)
      LOGICAL LORXER2(MAXER2LBL,2)

      CHARACTER*8 LBLER2(MAXER2LBL,2)

#if defined (SYS_CRAY)
      REAL EIGER2(MAXER2LBL)
      REAL FRQER2(MAXER2LBL,2)
#else
      DOUBLE PRECISION EIGER2(MAXER2LBL)
      DOUBLE PRECISION FRQER2(MAXER2LBL,2)
#endif

      COMMON/IER2RSP/ ISTER2, ISYSER2, ISYOER2, LPRER2, LORXER2,
     &                NER2LBL, ISYOFER2(8), LER2OPN
      COMMON/CER2RSP/ LBLER2
      COMMON/RER2RSP/ EIGER2, FRQER2

