      INTEGER MXGROP, MXXGST
      PARAMETER ( MXGROP = 20, MXXGST = 100)

      INTEGER NAXGRO, NSEXGR,  NXGRST
      INTEGER IAXGRO, ISEXGR,  IXGRST, ISYOFXG

      LOGICAL XDIPMO, XQUADR, XNQCC, XRELCO, XSECMO, ALLEXE, SELXGR,
     *        SELXST

      COMMON /INFXGR/ NAXGRO, IAXGRO(MXGROP), NXGRST, NSEXGR,
     *               XDIPMO, XQUADR, XNQCC, XRELCO, XSECMO,
     *               ALLEXE, SELXGR, ISEXGR(MXXGST,2), IXGRST(MXXGST),
     *               ISYOFXG(8)
      COMMON /XSTINF/ SELXST

