#if defined (SYS_CRAY)
      REAL EFIELD
#else
      DOUBLE PRECISION EFIELD
#endif
      INTEGER MXFELT, NFIELD
      PARAMETER (MXFELT = 20)
      CHARACTER*8 LFIELD
      LOGICAL  NONHF, NHFFIELD
      COMMON /CCFIELD/ NFIELD,NONHF,EFIELD(MXFELT),LFIELD(MXFELT),
     &                 NHFFIELD(MXFELT)
