      INTEGER MAXZLBL
      PARAMETER ( MAXZLBL = 100 )
      LOGICAL LORXLRZ, LL1OPN
      INTEGER NLRZLBL,ISYLRZ,ISYOFZ
      CHARACTER*8 LRZLBL

#if defined (SYS_CRAY)
      REAL FRQLRZ,XLRZ
#else
      DOUBLE PRECISION FRQLRZ,XLRZ
#endif

      COMMON/ILRZRSP/ NLRZLBL,ISYLRZ(MAXZLBL),ISYOFZ(8),
     &                LORXLRZ(MAXZLBL), LL1OPN
      COMMON/CLRZRSP/ LRZLBL(MAXZLBL)
      COMMON/RLRZRSP/ FRQLRZ(MAXZLBL),XLRZ(MAXZLBL)
