      INTEGER MAXL2LBL
      PARAMETER ( MAXL2LBL = 240 )

      LOGICAL LL2OPN
      INTEGER NL2LBL, ISYOFL2

      INTEGER ISYAL2(MAXL2LBL),ISYBL2(MAXL2LBL)
      INTEGER ISYL2(MAXL2LBL,2)
      EQUIVALENCE (ISYAL2(1),ISYL2(1,1) )
      EQUIVALENCE (ISYBL2(1),ISYL2(1,2) )

      CHARACTER*8 LBLAL2(MAXL2LBL), LBLBL2(MAXL2LBL)
      CHARACTER*8 LBLL2(MAXL2LBL,2)
      EQUIVALENCE (LBLAL2(1),LBLL2(1,1) )
      EQUIVALENCE (LBLBL2(1),LBLL2(1,2) )

      LOGICAL LORXAL2(MAXL2LBL), LORXBL2(MAXL2LBL)
      LOGICAL LORXL2(MAXL2LBL,2)
      EQUIVALENCE (LORXAL2(1),LORXL2(1,1) )
      EQUIVALENCE (LORXBL2(1),LORXL2(1,2) )

#if defined (SYS_CRAY)
      REAL FRQAL2(MAXL2LBL), FRQBL2(MAXL2LBL)
      REAL FRQL2(MAXL2LBL,2)
#else
      DOUBLE PRECISION FRQAL2(MAXL2LBL), FRQBL2(MAXL2LBL)
      DOUBLE PRECISION FRQL2(MAXL2LBL,2)
#endif
      EQUIVALENCE (FRQAL2(1),FRQL2(1,1) )
      EQUIVALENCE (FRQBL2(1),FRQL2(1,2) )

      COMMON/IL2RSP/ ISYL2, NL2LBL, ISYOFL2(8), LORXL2, LL2OPN
      COMMON/CL2RSP/ LBLL2
      COMMON/RL2RSP/ FRQL2

