      INTEGER MAXL3LBL
      PARAMETER ( MAXL3LBL = 120 )

      LOGICAL LL3OPN
      INTEGER NL3LBL, ISYOFL3

      INTEGER ISYL3(MAXL3LBL,3)

      CHARACTER*8 LBLL3(MAXL3LBL,3)

      LOGICAL LORXL3(MAXL3LBL,3)

#if defined (SYS_CRAY)
      REAL FRQL3(MAXL3LBL,3)
#else
      DOUBLE PRECISION FRQL3(MAXL3LBL,3)
#endif

      COMMON/IL3RSP/ ISYL3, NL3LBL, ISYOFL3(8), LORXL3, LL3OPN
      COMMON/CL3RSP/ LBLL3
      COMMON/RL3RSP/ FRQL3

