      INTEGER MAXL4LBL
      PARAMETER ( MAXL4LBL = 1 )

      LOGICAL LL4OPN
      INTEGER NL4LBL, ISYOFL4

      INTEGER ISYL4(MAXL4LBL,4)

      CHARACTER*8 LBLL4(MAXL4LBL,4)

      LOGICAL LORXL4(MAXL4LBL,4)

#if defined (SYS_CRAY)
      REAL FRQL4(MAXL4LBL,4)
#else
      DOUBLE PRECISION FRQL4(MAXL4LBL,4)
#endif

      COMMON/IL4RSP/ ISYL4, NL4LBL, ISYOFL4(8), LORXL4, LL4OPN
      COMMON/CL4RSP/ LBLL4
      COMMON/RL4RSP/ FRQL4

