      INTEGER MAXLC1LBL
      PARAMETER ( MAXLC1LBL = 60 )
      INTEGER NLC1LBL,ISYLC1,ISYOFLC1,ILC1CAU
      CHARACTER*8 LBLLC1
      LOGICAL LLC1OPN

      COMMON/ILC1RSP/ NLC1LBL,ISYLC1(MAXLC1LBL),ISYOFLC1(8),
     &                ILC1CAU(MAXLC1LBL), LLC1OPN
      COMMON/CLC1RSP/ LBLLC1(MAXLC1LBL)
