      INTEGER MAXM    
      PARAMETER ( MAXM    = 60 )
      INTEGER NLRM,ISYLRM,ISYOFM,ILRM

#if defined (SYS_CRAY)
      REAL FRQLRM
#else
      DOUBLE PRECISION FRQLRM
#endif

      COMMON/ILRMRSP/ NLRM,ISYLRM(MAXM),ISYOFM(8),ILRM(MAXM)
      COMMON/RLRMRSP/ FRQLRM(MAXM)
