      INTEGER MAXZLBL
      PARAMETER ( MAXZLBL = 60 )

      INTEGER NLRZLBL,ISYLRZ,ISYOFZ
      CHARACTER*8 LRZLBL

#if defined (SYS_CRAY)
      REAL FRQLRZ
#else
      DOUBLE PRECISION FRQLRZ
#endif

      COMMON/ILRZRSP/ NLRZLBL,ISYLRZ(MAXZLBL),ISYOFZ(8)
      COMMON/CLRZRSP/ LRZLBL(MAXZLBL)
      COMMON/RLRZRSP/ FRQLRZ(MAXZLBL)
