      INTEGER MXLROP, MBLRFR, MORGIN
      PARAMETER ( MXLROP = 100 , MBLRFR = 60, MORGIN = 50)

      INTEGER NBLRFR, NLRDISP, IPRSOP, NORGIN

      INTEGER NLROP, IALROP, IBLROP, NALROP, NBLROP, OFFALPHA(2)

      LOGICAL DIPPOL,ASYMSD,CAUCHY, LALORX, LBLORX, ALLLRDSPCF
      LOGICAL ALPHA_ISO, ALPHA_ANI, DIPGRA
      LOGICAL ORLEN, ORVEL, ORMVE, ORGANL

      CHARACTER*(8) CSYM

      REAL*8  ALRFR, BLRFR, ORGIN

      COMMON /INFPOL/ ALRFR(MBLRFR), BLRFR(MBLRFR), ORGIN(3,0:MORGIN),
     *                IALROP(MXLROP),IBLROP(MXLROP),
     *                LALORX(MXLROP),LBLORX(MXLROP),
     *                NALROP(8), NBLROP(8), NORGIN,
     *                DIPPOL,ASYMSD,ALLLRDSPCF,
     *                ORLEN,ORVEL,ORMVE,ORGANL,
     *                NBLRFR,CAUCHY,NLRDISP,
     *                NLROP, IPRSOP, OFFALPHA,
     *                ALPHA_ISO, ALPHA_ANI, DIPGRA,
     *                CSYM


