      INTEGER MAXTLBL
      PARAMETER ( MAXTLBL = 500 )
      INTEGER NLRTLBL,ISYLRT,ISYOFT
      CHARACTER*8 LRTLBL

#if defined (SYS_CRAY)
      REAL FRQLRT
#else
      DOUBLE PRECISION FRQLRT
#endif

      COMMON/ILRTRSP/ NLRTLBL,ISYLRT(MAXTLBL),ISYOFT(8)
      COMMON/CLRTRSP/ LRTLBL(MAXTLBL)
      COMMON/RLRTRSP/ FRQLRT(MAXTLBL)
