      INTEGER MXMCDOP, MXMCDST
      PARAMETER ( MXMCDOP = 125 , MXMCDST = 50 )

      INTEGER IPRMCD, NMCDST, NMCDOPER

      LOGICAL LAMCDRX, LBMCDRX, LCMCDRX
      INTEGER IAMCDOP, IBMCDOP, ICMCDOP
      LOGICAL LUSE2N1, SELMCDST, LUSEPL1

      INTEGER NMCDSELX, IMCDSELX, IMCDSL, IMCDSEL
      INTEGER IMCDSTSY, IMCDSTNR

      COMMON /INFMCDCC/
     *        IAMCDOP(MXMCDOP),IBMCDOP(MXMCDOP),ICMCDOP(MXMCDOP),
     *        LAMCDRX(MXMCDOP),LBMCDRX(MXMCDOP),LCMCDRX(MXMCDOP),
     *                 NMCDST, IPRMCD, NMCDOPER, NMCDSELX(8), 
     *                 IMCDSELX(8),
     *                 IMCDSTSY(MXMCDST),IMCDSTNR(MXMCDST),
     *                 SELMCDST,LUSEPL1,LUSE2N1 
