      INTEGER MAXQRN2 
      PARAMETER ( MAXQRN2  = 100 )

      LOGICAL LN2OPN
      INTEGER NQRN2,ISYOFN2

      INTEGER ISYSN2(MAXQRN2,2)
      INTEGER ISYIN2(MAXQRN2), ISYFN2(MAXQRN2)
      EQUIVALENCE (ISYIN2(1),ISYSN2(1,1))
      EQUIVALENCE (ISYFN2(1),ISYSN2(1,2))

      INTEGER ISTN2(MAXQRN2,2)
      INTEGER IIN2(MAXQRN2), IFN2(MAXQRN2)
      EQUIVALENCE (IIN2(1),ISTN2(1,1))
      EQUIVALENCE (IFN2(1),ISTN2(1,2))

#if defined (SYS_CRAY)
      REAL EIGN2(MAXQRN2,2)
      REAL FRQIN2(MAXQRN2), FRQFN2(MAXQRN2)
#else
      DOUBLE PRECISION EIGN2(MAXQRN2,2)
      DOUBLE PRECISION FRQIN2(MAXQRN2), FRQFN2(MAXQRN2)
#endif
      EQUIVALENCE (FRQIN2(1),EIGN2(1,1))
      EQUIVALENCE (FRQFN2(1),EIGN2(1,2))

C     COMMON/IN2RSP/ NQRN2, ISYOFN2(8), LN2OPN,
C    &               ISYIN2(MAXQRN2),ISYFN2(MAXQRN2),
C    &               IIN2(MAXQRN2),IFN2(MAXQRN2)
C     COMMON/RN2RSP/ FRQIN2(MAXQRN2),FRQFN2(MAXQRN2)

      COMMON/IN2RSP/ ISYSN2, ISTN2, NQRN2, ISYOFN2(8), LN2OPN
      COMMON/RN2RSP/ EIGN2

