      INTEGER MAXO1LBL
      PARAMETER ( MAXO1LBL = 120 )

      LOGICAL LO1OPN
      INTEGER NO1LBL,ISYOFO1

      LOGICAL LORXO1(MAXO1LBL)
      INTEGER ISYO1(MAXO1LBL)
      CHARACTER*8 LBLO1(MAXO1LBL)

#if defined (SYS_CRAY)
      REAL FRQO1(MAXO1LBL)
#else
      DOUBLE PRECISION FRQO1(MAXO1LBL)
#endif


      COMMON/IO1RSP/ ISYO1, NO1LBL, ISYOFO1(8), LO1OPN, LORXO1
      COMMON/CO1RSP/ LBLO1
      COMMON/RO1RSP/ FRQO1

