      INTEGER MAXO2LBL
      PARAMETER ( MAXO2LBL = 120 )

      LOGICAL LO2OPN
      INTEGER NO2LBL,ISYOFO2

      INTEGER ISYAO2(MAXO2LBL), ISYBO2(MAXO2LBL)
      INTEGER ISYO2(MAXO2LBL,2)
      EQUIVALENCE (ISYAO2(1),ISYO2(1,1) )
      EQUIVALENCE (ISYBO2(1),ISYO2(1,2) )


      CHARACTER*8 LBLAO2(MAXO2LBL), LBLBO2(MAXO2LBL)
      CHARACTER*8 LBLO2(MAXO2LBL,2)
      EQUIVALENCE (LBLAO2(1),LBLO2(1,1) )
      EQUIVALENCE (LBLBO2(1),LBLO2(1,2) )

      LOGICAL LORXAO2(MAXO2LBL), LORXBO2(MAXO2LBL)
      LOGICAL LORXO2(MAXO2LBL,2)
      EQUIVALENCE (LORXAO2(1),LORXO2(1,1) )
      EQUIVALENCE (LORXBO2(1),LORXO2(1,2) )     

#if defined (SYS_CRAY)
      REAL FRQAO2(MAXO2LBL), FRQBO2(MAXO2LBL)
      REAL FRQO2(MAXO2LBL,2)
#else
      DOUBLE PRECISION FRQAO2(MAXO2LBL), FRQBO2(MAXO2LBL)
      DOUBLE PRECISION FRQO2(MAXO2LBL,2)
#endif
      EQUIVALENCE (FRQAO2(1),FRQO2(1,1) )
      EQUIVALENCE (FRQBO2(1),FRQO2(1,2) )

      COMMON/IO2RSP/ ISYO2, NO2LBL, ISYOFO2(8), LO2OPN, LORXO2
      COMMON/CO2RSP/ LBLO2
      COMMON/RO2RSP/ FRQO2

