      INTEGER MAXO3LBL
      PARAMETER ( MAXO3LBL = 240 )

      LOGICAL LO3OPN
      INTEGER NO3LBL,ISYOFO3

      INTEGER ISYO3(MAXO3LBL,3)

      CHARACTER*8 LBLO3(MAXO3LBL,3)

      LOGICAL LORXO3(MAXO3LBL,3)

#if defined (SYS_CRAY)
      REAL FRQO3(MAXO3LBL,3)
#else
      DOUBLE PRECISION FRQO3(MAXO3LBL,3)
#endif

      COMMON/IO3RSP/ ISYO3, NO3LBL, ISYOFO3(8), LO3OPN, LORXO3
      COMMON/CO3RSP/ LBLO3
      COMMON/RO3RSP/ FRQO3

