      INTEGER MAXO4LBL
      PARAMETER ( MAXO4LBL = 1 )

      LOGICAL LO4OPN
      INTEGER NO4LBL,ISYOFO4

      INTEGER ISYO4(MAXO4LBL,4)

      CHARACTER*8 LBLO4(MAXO4LBL,4)

      LOGICAL LORXO4(MAXO4LBL,4)

#if defined (SYS_CRAY)
      REAL FRQO4(MAXO4LBL,4)
#else
      DOUBLE PRECISION FRQO4(MAXO4LBL,4)
#endif

      COMMON/IO4RSP/ ISYO4, NO4LBL, ISYOFO4(8), LO4OPN, LORXO4
      COMMON/CO4RSP/ LBLO4
      COMMON/RO4RSP/ FRQO4

