      INTEGER MXQROP, MXQRFR, MXQRDISP
      PARAMETER ( MXQROP = 125 , MXQRFR = 20, MXQRDISP = 322 )

      LOGICAL BETA_AVERAGE, XY_DEGENERAT, USEBTRAN, USE_R2, ALLDSPCF,
     &        USE_AAMAT, LAVANEW

      INTEGER IPRQHYP, NQRFREQ, NQROPER, NQRDISP, NQRDSPE, NQRDSPO

      LOGICAL LAQLRX, LBQLRX, LCQLRX
      INTEGER IAQROP, IBQROP, ICQROP
      INTEGER IQCAUA, IQCAUB, IQCAUC

#if defined (SYS_CRAY)
      REAL AQRFR, BQRFR, CQRFR, DIPSAVE
#else
      DOUBLE PRECISION AQRFR, BQRFR, CQRFR, DIPSAVE
#endif
      COMMON /INFHYPCC/ AQRFR(MXQRFR),  BQRFR(MXQRFR),  CQRFR(MXQRFR),
     *                 IAQROP(MXQROP), IBQROP(MXQROP), ICQROP(MXQROP),
     *                 LAQLRX(MXQROP), LBQLRX(MXQROP), LCQLRX(MXQROP),
     *             IQCAUA(MXQRDISP),IQCAUB(MXQRDISP),IQCAUC(MXQRDISP),
     *                 NQRFREQ, NQROPER, NQRDISP, NQRDSPE, NQRDSPO,
     *                 IPRQHYP, BETA_AVERAGE, XY_DEGENERAT, 
     *                 USEBTRAN, USE_R2, ALLDSPCF, USE_AAMAT,DIPSAVE(3),
     *                 LAVANEW


