      INTEGER MAXT2LBL
      PARAMETER ( MAXT2LBL = 120 )
      INTEGER NR2TLBL,ISYAR2T,ISYBR2T,ISYOFT2
      CHARACTER*8 LBLAR2T, LBLBR2T
      LOGICAL LR2OPN

#if defined (SYS_CRAY)
      REAL FRQAR2T, FRQBR2T
#else
      DOUBLE PRECISION FRQAR2T, FRQBR2T
#endif

      COMMON/IR2TRSP/ NR2TLBL, ISYOFT2(8), LR2OPN,
     &                ISYAR2T(MAXT2LBL),ISYBR2T(MAXT2LBL)
      COMMON/CR2TRSP/ LBLAR2T(MAXT2LBL),LBLBR2T(MAXT2LBL)
      COMMON/RR2TRSP/ FRQAR2T(MAXT2LBL),FRQBR2T(MAXT2LBL)
