      INTEGER MAXT2LBL
      PARAMETER ( MAXT2LBL = 120 )

      LOGICAL LR2OPN
      INTEGER NR2TLBL, ISYOFT2

      INTEGER ISYAR2T(MAXT2LBL),ISYBR2T(MAXT2LBL)
      INTEGER ISYR2T(MAXT2LBL,2)
      EQUIVALENCE (ISYAR2T(1),ISYR2T(1,1) )
      EQUIVALENCE (ISYBR2T(1),ISYR2T(1,2) )

      CHARACTER*8 LBLAR2T(MAXT2LBL), LBLBR2T(MAXT2LBL)
      CHARACTER*8 LBLR2T(MAXT2LBL,2)
      EQUIVALENCE (LBLAR2T(1),LBLR2T(1,1) )
      EQUIVALENCE (LBLBR2T(1),LBLR2T(1,2) )

      LOGICAL LORXAR2T(MAXT2LBL), LORXBR2T(MAXT2LBL)
      LOGICAL LORXR2T(MAXT2LBL,2)
      EQUIVALENCE (LORXAR2T(1),LORXR2T(1,1) )
      EQUIVALENCE (LORXBR2T(1),LORXR2T(1,2) )

#if defined (SYS_CRAY)
      REAL FRQAR2T(MAXT2LBL), FRQBR2T(MAXT2LBL)
      REAL FRQR2T(MAXT2LBL,2)
#else
      DOUBLE PRECISION FRQAR2T(MAXT2LBL), FRQBR2T(MAXT2LBL)
      DOUBLE PRECISION FRQR2T(MAXT2LBL,2)
#endif
      EQUIVALENCE (FRQAR2T(1),FRQR2T(1,1) )
      EQUIVALENCE (FRQBR2T(1),FRQR2T(1,2) )

      COMMON/IR2TRSP/ ISYR2T, NR2TLBL, ISYOFT2(8), LORXR2T, LR2OPN
      COMMON/CR2TRSP/ LBLR2T
      COMMON/RR2TRSP/ FRQR2T

