      INTEGER MAXT3LBL
      PARAMETER ( MAXT3LBL = 240 )

      LOGICAL LR3OPN
      INTEGER NR3TLBL, ISYOFT3

      INTEGER ISYR3T(MAXT3LBL,3)

      CHARACTER*8 LBLR3T(MAXT3LBL,3)

      LOGICAL LORXR3T(MAXT3LBL,3)

#if defined (SYS_CRAY)
      REAL FRQR3T(MAXT3LBL,3)
#else
      DOUBLE PRECISION FRQR3T(MAXT3LBL,3)
#endif

      COMMON/IR3TRSP/ ISYR3T, NR3TLBL, ISYOFT3(8), LORXR3T, LR3OPN
      COMMON/CR3TRSP/ LBLR3T
      COMMON/RR3TRSP/ FRQR3T

