      INTEGER MAXT4LBL
      PARAMETER ( MAXT4LBL = 1 )

      LOGICAL LR4OPN
      INTEGER NR4TLBL, ISYOFT4

      INTEGER ISYR4T(MAXT4LBL,4)

      CHARACTER*8 LBLR4T(MAXT4LBL,4)

      LOGICAL LORXR4T(MAXT4LBL,4)

#if defined (SYS_CRAY)
      REAL FRQR4T(MAXT4LBL,4)
#else
      DOUBLE PRECISION FRQR4T(MAXT4LBL,4)
#endif

      COMMON/IR4TRSP/ ISYR4T, NR4TLBL, ISYOFT4(8), LORXR4T, LR4OPN
      COMMON/CR4TRSP/ LBLR4T
      COMMON/RR4TRSP/ FRQR4T

