      INTEGER MAXCLBL
      PARAMETER ( MAXCLBL = 60 )
      INTEGER NLRCLBL,ISYLRC,ISYOFC,ILRCAU
      CHARACTER*8 LRCLBL
      LOGICAL LRC1OPN

      COMMON/ILRCRSP/ NLRCLBL,ISYLRC(MAXCLBL),ISYOFC(8),
     &                ILRCAU(MAXCLBL),LRC1OPN
      COMMON/CLRCRSP/ LRCLBL(MAXCLBL)
