      INTEGER MAXOP2LBL
      PARAMETER ( MAXOP2LBL = 60 )
      LOGICAL LOPR2OPN, LPDBSOP2, LQUIET
      INTEGER NRSO2LBL, ISYOP2, ISYOFOP2, ISYMAT2, IATOPR2, ISGNOP2
      CHARACTER*8 LBLOP2

      COMMON /IRSOPR2/ ISYOP2(MAXOP2LBL),ISYMAT2(MAXOP2LBL),
     &                 IATOPR2(MAXOP2LBL),ISGNOP2(MAXOP2LBL),
     &                 ISYOFOP2(8), NRSO2LBL, LOPR2OPN, LQUIET,
     &                 LPDBSOP2(MAXOP2LBL)
      COMMON /CRSOPR2/ LBLOP2(MAXOP2LBL,3)
