      INTEGER MAXOLBL
      PARAMETER ( MAXOLBL = 100 )
      LOGICAL LOPROPN, LPDBSOP
      INTEGER NRSOLBL, ISYOPR, ISYOFO, ISYMAT, IATOPR
      CHARACTER*8 LBLOPR
      CHARACTER*12 CONNECTION

      COMMON /IRSOPER/ ISYOPR(MAXOLBL),ISYMAT(MAXOLBL),IATOPR(MAXOLBL),
     &                 ISYOFO(8), NRSOLBL, LOPROPN, LPDBSOP(MAXOLBL)
      COMMON /CRSOPER/ LBLOPR(MAXOLBL), CONNECTION
