      INTEGER MXCCSL,MAXCCL
      PARAMETER (MXCCSL = 100,MAXCCL=15)

      INTEGER NCCSLV,MXCCSLIT,ICCSLIT,LMAXCC
      INTEGER LMAXCU,NLMCU
      INTEGER ISYTLM
      INTEGER NSLVINIT, MXTINIT, MXLINIT

      LOGICAL PTSOLV 
      LOGICAL LSLECVG,LSLTCVG,LSLLCVG,LSTBTR
      LOGICAL LRSPFUL,LOITER
      LOGICAL DISCEX

#if defined (SYS_CRAY)
      REAL RCAVCC,EPSTCC,EPOPCC,CVGESOL,CVGTSOL,CVGLSOL
      REAL EPSTCU,EPOPCU,RCAVCU,ECCCU,XTNCCCU,XLNCCCU
      REAL ECCPR,XTNCCPR,XLNCCPR
      REAL ECCSL,XTNCCSL,XLNCCSL,CCTLM
#else
      DOUBLE PRECISION RCAVCC,EPSTCC,EPOPCC,CVGESOL,CVGTSOL,CVGLSOL
      DOUBLE PRECISION EPSTCU,EPOPCU,RCAVCU,ECCCU,XTNCCCU,XLNCCCU
      DOUBLE PRECISION ECCPR,XTNCCPR,XLNCCPR
      DOUBLE PRECISION ECCSL,XTNCCSL,XLNCCSL,CCTLM
#endif

      COMMON /ISLVINP/ NCCSLV,MXCCSLIT,ICCSLIT,LMAXCC(MXCCSL)
      COMMON /LSLVINP/ PTSOLV
      COMMON /RSLVINP/ RCAVCC(MXCCSL),EPSTCC(MXCCSL),EPOPCC(MXCCSL),
     *                 CVGESOL,CVGTSOL,CVGLSOL
      COMMON /SLVCUR/ EPSTCU,EPOPCU,
     *                RCAVCU,ECCCU,XTNCCCU,XLNCCCU,
     *                LMAXCU,NLMCU,ISYTLM(2*MAXCCL+1)
      COMMON /SLVPRE/ ECCPR,XTNCCPR,XLNCCPR
      COMMON /SLVCVG/ LSLECVG,LSLTCVG,LSLLCVG,LSTBTR,
     *                ECCSL,XTNCCSL,XLNCCSL
      COMMON /ISLVCNV/ NSLVINIT, MXTINIT, MXLINIT
      COMMON /CCGINF/ CCTLM(MAXCCL*MAXCCL)
      COMMON /CCSLVL/ LRSPFUL,LOITER,DISCEX

