      INTEGER MXTMOP, MXTMSEL

      PARAMETER ( MXTMOP = 900 , MXTMSEL = 50 )

      INTEGER IPRTM, NTMSEL, NTMOPER

      INTEGER IATMOP, IBTMOP, ICTMOP, IDTMOP, IETMOP, IFTMOP
     
      INTEGER NTMSELX, ITMSELX, ITMSEL

#if defined (SYS_CRAY)
      REAL EXTMFR, BTMFR, CTMFR
#else
      DOUBLE PRECISION EXTMFR, BTMFR, CTMFR
#endif
      COMMON /INFTMCC/  EXTMFR(MXTMSEL), BTMFR(MXTMSEL), CTMFR(MXTMSEL),
     *                   ITMSEL(MXTMSEL,2), 
     *                   IATMOP(MXTMOP), IBTMOP(MXTMOP), ICTMOP(MXTMOP),
     *                   IDTMOP(MXTMOP), IETMOP(MXTMOP), IFTMOP(MXTMOP),
     *                   NTMSEL, IPRTM, NTMOPER,
     *                   NTMSELX(8), ITMSELX(8)
