      INTEGER MAXX3LBL
      PARAMETER ( MAXX3LBL = 120 )

      LOGICAL LX3OPN
      INTEGER NX3LBL, ISYOFX3

      INTEGER ISYX3(MAXX3LBL,3)

      CHARACTER*8 LBLX3(MAXX3LBL,3)

      LOGICAL LORXX3(MAXX3LBL,3)

#if defined (SYS_CRAY)
      REAL FRQX3(MAXX3LBL,3)
#else
      DOUBLE PRECISION FRQX3(MAXX3LBL,3)
#endif

      COMMON/IX3RSP/ ISYX3, NX3LBL, ISYOFX3(8), LX3OPN, LORXX3
      COMMON/CX3RSP/ LBLX3
      COMMON/RX3RSP/ FRQX3

