      INTEGER MXQR2O, MXQR2ST
      PARAMETER ( MXQR2O = 60, MXQR2ST = 60)

      INTEGER NQR2OP, NXQR2ST, NSEQR2

      INTEGER IQR2OP, IQR2ST, ISEQR2SYM, ISEQR2STA

      LOGICAL QR22N1, SELQR2

      COMMON /INFXOPA/ IQR2ST(MXQR2ST,2),
     *                 ISEQR2SYM(MXQR2ST,2),
     *                 ISEQR2STA(MXQR2ST,2),
     *                 IQR2OP(MXQR2O),
     *                 NQR2OP,NSEQR2,NXQR2ST,
     *                 QR22N1,SELQR2


