      INTEGER MXBSCE, MXACAT, MXACBS
      PARAMETER (MXBSCE = 2000, MXACAT = 50, MXACBS = 5000)
      PARAMETER (MXEXBS = 500)
C
      DOUBLE PRECISION THACOC, THACVI
C
      INTEGER NBCENT, IBCENT, NBSCEN, KBSCEN, 
     &        NACATM, LACTAT, LACBAS, NACTBS, NABSTO,
     &        NACTOC, NACTVI, NINAOC, NINAVI,
     &        IORACT, NORACT, NACTFR, NEXTBS, IEXTBS,
     &        NOCVEC, NVIVEC, NACINP, LACINP, IORDEC,
     &        NSELD,  ISELD,  NFRACT, NOPSHL, NACTOP, NOPVEC
C
      LOGICAL ACTIVE, ATOMIC, ACTFRE, DIFADD, NBOEXP, SELDIR,
     &        OPNSHL, DIASEL, FULDEC
C
      COMMON /CENTER/ THACOC, THACVI,
     &                NBCENT(MXCENT,8), IBCENT(MXCENT,8),
     &                NBSCEN(MXCENT), KBSCEN(MXBSCE,MXCENT),
     &                NACATM, LACTAT(MXACAT), LACBAS(MXACBS),
     &                NACTBS(8), NABSTO, NACTFR, 
     &                IORACT(8), NORACT(8),
     &                NACTOC(8), NACTVI(8), NINAOC(8), NINAVI(8),
     &                NEXTBS(8), IEXTBS(MXEXBS,8),
     &                NOCVEC(MXCENT,8), NVIVEC(MXCENT,8), 
     &                NACINP, LACINP(MXACAT), IORDEC(MXCENT),
     &                NSELD(MXACAT), ISELD(MXBSCE,MXACAT), NFRACT(8),
     &                NOPSHL(8), NOPVEC(MXCENT,8), NACTOP(8),
     &                ACTIVE, ATOMIC, ACTFRE, DIFADD, NBOEXP, SELDIR,
     &                OPNSHL,DIASEL(MXACAT), FULDEC
C

