C Stuff for Cholesky CC2:
      LOGICAL CHOT2, CHOMO2, CHOT2C, DSKETA, DSKFY2
      PARAMETER (LCC2YM = 90)
      CHARACTER*11 FCC2S
      PARAMETER (FCC2S = 'CHOMO2.INFO')
      CHARACTER*10 FDEN00
      PARAMETER (FDEN00 = 'DENSITY_00')
      CHARACTER*7 FCC2YM(8)
      COMMON / CHOCC2 / CHOT2,CHOMO2,CHOT2C,DSKETA,DSKFY2
      COMMON / MOCHO2 / NCHMO2(8),MXDEC2,NCHRD2
      COMMON / MOCHOC / NCHMOC(8),MXDECC,NCHRDC
      COMMON / MODIA2 / THRCC2,SPACC2,THZCC2
      COMMON / MODIAC / THRCCC,SPACCC
      COMMON / SPLCC2 / SPLITC
      COMMON / ALGCC2 / IALCC2
      DATA FCC2YM /'CC2YM_1','CC2YM_2','CC2YM_3','CC2YM_4',
     &             'CC2YM_5','CC2YM_6','CC2YM_7','CC2YM_8'/

