      INTEGER*8 MAXLEN
      INTEGER JFINIS,JADR,IADR
      INTEGER IADRTO(8),IADRLU(0:9,1:8)
C
      COMMON /CHOIO/ MAXLEN,IADRTO,IADRLU,
     &               IDNTLU(0:9,1:8),NUMFIL(8),IGB
C
      INTEGER LUDIAG,LURST,LUSEC
      COMMON /CHOLUN/ LUDIAG,LURST,LUSEC

