      LOGICAL MP2SAV,CHOMO,SKIPTR,SKIPCH,SPRMP2
      CHARACTER*10 FMP2S
      PARAMETER (FMP2S = 'CHOMO.INFO')
      COMMON / CHOMP2 / MP2SAV,CHOMO,SKIPTR,SKIPCH,SPRMP2
      COMMON / MOCHO  / NCHOMO(8),MXDECM,NCHORD
      COMMON / MODIA  / THRMP2,SPAMP2,SCRMP2,SPLITM,THZMP2
      COMMON / ALGMP2 / IALMP2

