C Info for Cholesky based SCF:
C
      LOGICAL CCMODSK, ITSLDA
      CHARACTER*6 FCCMO
C
      COMMON / CHOSCF / NDVCS(8)
      COMMON / CSCFNT / LUCCMO
      COMMON / CSCFIL / FCCMO
      COMMON / CSCFMO / CCMODSK
      COMMON / DENTHR / THRDC
      COMMON / CHOLDA / ITSLDA

