      LOGICAL         DHCHX, DHCHY,  DHCHZ,  DHCEX, DHCEX1, DHCEX2,
     &                DHCEY, DHCEY1, DHCEY2, DHCEZ, DHCEZ1, DHCEZ2
      COMMON /CRSDIR/ DHCHX, DHCHY,  DHCHZ,  DHCEX, DHCEX1, DHCEX2,
     &                DHCEY, DHCEY1, DHCEY2, DHCEZ, DHCEZ1, DHCEZ2
