C     Codes for call of DAFILE
      INTEGER DASKIP,DAWRIT,DAREAD,DAGWRI,DASREA,
     &        DAREW, DAAWRI,DAAREA,DAAGWR,DAAGRE
      PARAMETER (DASKIP = 0, DAWRIT = 1, DAREAD = 2, DAGWRI = 3,
     &           DASREA = 4, DAREW  = 5, DAAWRI = 6, DAAREA = 7,
     &           DAAGWR = 8, DAAGRE = 9)
