      LOGICAL DODRC,DOVWN,DOBCK,DOLYP,DOGGA,DOGRHO,DOLRHO,DOKT,FROMVX
      COMMON/DFTLBF/DODRC,DOVWN,DOBCK,DOLYP,DOGGA,DOGRHO,DOLRHO,DOKT,
     &              FROMVX
      COMMON/DFTRBF/FACDRC,FACVWN,FACBCK,FACLYP,FACKT,ELCTRN,
     &              ERGDRC,ERGVWN,ERGBCK,ERGLYP,ERGKT, 
     &              ED,EV,EB,EL,EK,VD,VV,VB1,VB2,VL1,VL2,VK1,VK2,
     &              VDRC1 ,VVWN1 ,FR0BCK,FR0LYP,FZ0BCK,FZ0LYP,FRRDRC,
     &              FRRVWN,FRRBCK,FRRLYP,FRZDRC,FRZVWN,FRZBCK,FRZLYP
      COMMON/DFTIBF/NDER
