      INTEGER MXCALL
      INTEGER ICLFRS, ICLLST, ICLBCH, ICLDST
      COMMON /DISTCL/ MXCALL,
     &                ICLFRS(MXSHEL), ICLLST(MXSHEL),
     &                ICLBCH(MXSHEL), ICLDST(MXSHEL)
