      INTEGER LBUF, NBUFS, NIBUF, NBITS, NBUFX, LUAORC
      LOGICAL NEWDIS
      COMMON /ERIBUF/ LBUF, NBUFS, NIBUF, NBITS, NBUFX(0:MXCOOR),
     &                NEWDIS
      COMMON /ERITAP/ LUAORC(0:MXCOOR)
