      INTEGER IPTRAB, NASTXP
      LOGICAL FTRONV, GTRONV, HTRONV, RTRONV, FTWOXP, SORTXP,
     &                PTRTXP, NPVTXP, FABRHS, FTRCTL
      COMMON /EXEINF/ FTRONV, GTRONV, HTRONV, RTRONV, NASTXP, FTWOXP,
     &                SORTXP, PTRTXP, NPVTXP, FABRHS, FTRCTL, IPTRAB
