      PARAMETER ( MAXLC6 = MAXLBL )
      LOGICAL LC6OP,PADE,GSLEGN,C6IFC
      CHARACTER*8 LBLC6
      COMMON /INFC6/  THCC6, THCMOM ,  IPRC6,  MAXITC, MAXMOM, PADE,
     *                GSLEGN , NGRID, NGPC6(8),  LC6OP(MAXLC6), C6IFC
      COMMON /CHRC6/  LBLC6(8,MAXLC6)
