      INTEGER MAXLLR
      PARAMETER ( MAXLLR = MAXLBL )
      LOGICAL LLROP, SOPRSY, LQRGP
      CHARACTER*8 LBLLR
#if defined (SYS_CRAY) || defined (SYS_T3D) || defined (VAR_REAL) || defined (SYS_T90)
      REAL THCLR, THRNRM
#else
      DOUBLE PRECISION THCLR, THRNRM
#endif
      INTEGER IPRLR, MAXITL, NGPLR, LRRANK
      COMMON /INFLR/  THCLR, THRNRM,  IPRLR,  MAXITL, NGPLR(8),
     *                LLROP(MAXLLR), SOPRSY, LRRANK(MAXLLR), LQRGP
      COMMON /CHRLR/  LBLLR(8,MAXLLR)
