      real(8) :: EMCSCF,EMCOLD,DEPRED,BETA,BETMIN,BETMAX, GNORM,GRDNRM
      real(8) :: RTRUST,RTTOL,RATMIN,RATGOD,EPOT,EMY,EACTIV,RATREJ
      real(8) :: SHFLVL,REJWMI,REJWMA,STPLEN,STPMAX,STPINC,STPRED
      real(8) :: THQMIN,THQLIN,THQKVA,GAMMA,RBETA,STPC,STPO,ESOLT,ECORR
      integer :: ITMAC,ITMICT,NREDL,NROOTC,JROOT
      COMMON /INFOPT/ EMCSCF,EMCOLD,DEPRED,BETA,BETMIN,BETMAX,          &
     &                GNORM(3),RTRUST,RTTOL,RATMIN,RATGOD,              &
     &                EPOT,EMY,EACTIV,RATREJ,SHFLVL,REJWMI,REJWMA,      &
     &                STPLEN,STPMAX,STPINC,STPRED,                      &
     &                THQMIN,THQLIN,THQKVA,GAMMA,RBETA,                 &
     &                ITMAC,ITMICT,NREDL,NROOTC,JROOT(10),              &
     &                STPC,STPO, ESOLT, ECORR
      EQUIVALENCE (GRDNRM,GNORM(3))
