      PARAMETER ( MXTMOP = MAXLBL , MBTMFR = MAXLBL, MCTMFR = MAXLBL)
      LOGICAL CTMOHG,TOMOM,ATMOP,BTMOP,CTMOP,THREEPHOTON
      CHARACTER*8 ATMLB,BTMLB,CTMLB
      COMMON /INFTMO/ CTMFR(MBTMFR), BTMFR(MBTMFR), NATMOP(8),
     *                NCTMOP(8), NBTMOP(8), NTMCNV(8),
     *                ATMOP(MXTMOP), BTMOP(MXTMOP),CTMOP(MXTMOP),
     *                CTMOHG,TOMOM,THREEPHOTON,IPRTMO,NBTMFR,NCTMFR
      COMMON /CHRTMO/ ATMLB(8,MXTMOP),BTMLB(8,MXTMOP),CTMLB(8,MXTMOP)
