C
      INTEGER NVSET,NV2LOC,NO2LOC,NOCLAB,NVILAB
      PARAMETER (NOV = 20, NOC = 20)
      PARAMETER ( NLABOC = 20, NLABVI = 20)
      CHARACTER TABOCL(NLABOC)*8,TABVIL(NLABVI)*8
      LOGICAL ABALOC, FOSOCC, FBOVIR, FBSETV, FBSTVO, MULLOC
      LOGICAL FBOCIN, LABOCC, LABVIR, FBOOCC
C
      COMMON /LOCINF/ ABALOC, FOSOCC, FBOVIR, FBSETV, FBSTVO, MULLOC,
     &                FBOCIN, LABOCC, LABVIR, FBOOCC,  NVSET,
     &                NTVI2L(NOV), NV2LOC, NO2LOC, NVILAB, NOCLAB,
     &                NTOC2L(NOC),TABOCL,TABVIL
C
