      INTEGER MAXTMP, ATMNUM 
      PARAMETER ( MAXTMP = 20 )
      PARAMETER ( ATMNUM = 20 ) 
      LOGICAL FCFLG,SDFLG
      INTEGER ESRNUC, NUCINF, SDIND
      INTEGER ISODAT
      
      DOUBLE PRECISION DEGEN, HYPVAL
      DOUBLE PRECISION SDVAL
      COMMON /INFNMR/ SDVAL(3,3,ATMNUM),
     *       HYPVAL(ATMNUM,2),DEGEN(ATMNUM),
     *       SDIND(2,3*ATMNUM),ISODAT(7,ATMNUM),
     *       NUCINF(ATMNUM), ESRNUC, 
     *       FCFLG, SDFLG
                     
