      LOGICAL       PASTWO, PASORT, PASDIP, PASONE, PASRES, PASREL,
     *              PASDPR, PASCRS, PASCZR, PASCTR, PASCRL, PASMAG,
     *              PASAAT, PASRTR, PASLRS, PASTRP, PASLNR, PASEXC,
     *              PASQPG
      COMMON /PAST/ PASTWO, PASORT, PASDIP, PASONE, PASRES, PASREL,
     *              PASDPR, PASCRS, PASCZR, PASCTR, PASCRL, PASMAG,
     *              PASAAT, PASRTR, PASLRS, PASTRP, PASLNR, PASEXC,
     *              PASQPG
