      LOGICAL       PSTWOB, PSORTB, PSDIPB, PSONEB, PSRESB, PSRELB,
     &              PSDPRB, PSCRSB, PSCZRB, PSCTRB, PSCRLB, PSMAGB,
     &              PSAATB, PSRTRB, PSLRSB, PSTRPB, PSLNRB, PSEXCB
      COMMON /PASTBK/ PSTWOB, PSORTB, PSDIPB, PSONEB, PSRESB, PSRELB,
     &              PSDPRB, PSCRSB, PSCZRB, PSCTRB, PSCRLB, PSMAGB,
     &              PSAATB, PSRTRB, PSLRSB, PSTRPB, PSLNRB, PSEXCB
