C
C     /PRIBAK/ is a copy of /INFPRI/
C
      LOGICAL P4FLGB,P6FLGB
      COMMON /PRIBAK/ IPRI4B,IPRI6B,IPRSRB,
     &                IPRCNB,IPRDIB,IPRSGB,IPDNSB,IPMP2B,IPRSLB,
     &                IPRKPB,IPRMLB,IPRCXB,IPRHFB,IPRAVB,IPRFCB,
     &                MPRI4B,MPRI6B,MPRSRB,
     &                P4FLGB(NPFLAG),P6FLGB(NPFLAG)
