C
C     Property information for calc. of numerical derivatives/vib. averages
C     of properties 
C     Tentative version Ove 250899
C
c     CHARACTER*8 LAB0, LAB1, LAB2, LAB3
c     CHARACTER*10 CPRPC
c     CHARACTER*8 LAB0O, LAB1O, LAB2O, LAB3O
c     CHARACTER*10 CPRPCO
c     PARAMETER (MXPRPC=500)
c     PARAMETER (THRZEP=1.0D-10)
c     COMMON /IPROPS/ NPRPC, IOPRPC(MXPRPC), ISAVSY(MXPRPC)
c     COMMON /PROPS/ PRPC(MXPRPC),FRQ1(MXPRPC),FRQ2(MXPRPC),
c    *               FRQ3(MXPRPC)
c     COMMON /CPROPS/ CPRPC(MXPRPC),LAB0(MXPRPC),LAB1(MXPRPC),
c    *                LAB2(MXPRPC),LAB3(MXPRPC)
c     COMMON /IPROPSO/ NPRPCO, IOPRPCO(MXPRPC), ISAVSYO(MXPRPC)
c     COMMON /PROPSO/ PRPCO(MXPRPC),FRQ1O(MXPRPC),FRQ2O(MXPRPC),
c    *               FRQ3O(MXPRPC)
c     COMMON /CPROPSO/ CPRPCO(MXPRPC),LAB0O(MXPRPC),LAB1O(MXPRPC),
c    *                LAB2O(MXPRPC),LAB3O(MXPRPC)
C A much slimmer version...
      PARAMETER (THRZEP=1.0D-10)
      COMMON /IPROPS/ NPRPC, NPRPCO, NPRPINSYM(8), NPRMI
