      COMMON /PTRBUF/ MX1BUF, L1BUF, MEMS, MEMT, MAXCHN, MXABUF, LABUF,
     *                LDAMAX, LASTAD(200), MX2BUF, L2BUF,  MAXSCM,
     *                MAXLCM, IADR(200),   NCHAIN, MAXADR, NBLOCK
