C --- FILE: qmmm.h ---
C
      LOGICAL SPLDIP,CONMAT,FIXDIP,MMDAMP,MMPROP,
     *        SPLNMR,MMMAT,MMITER,MMDIIS,LCLOSE,
     *        LMMNUL,ZEROOC,MMREST,RELMAT,LGFILE, LHFFIL,
     *        ZERODI,ZEROQU,ISOPOL,NOPOL,NOMB,MMTIME,
     *        NEWEXC
      INTEGER MMCENT,NMULT,IPOLTP,NEXLST,EXLIST,
     *        ZEROAL,NNZAL,IDAMP,NQMNUC,MXMMIT,
     *        MXMMDI,NMMAC,IQMMMC,
     *        NELEME,ELEME,IPQMMM,
     *        MXMMCT,MXEXCL
C 
      PARAMETER(MXMMCT = 90000)
      PARAMETER(MXEXCL = 200)

C
#if defined (SYS_CRAY)
      REAL MMCORD, MUL0MM, MUL1MM, MUL2MM, MUL3MM, 
     *     POLMM, POLIMM, THRMM, QMPOL, THMMIT, RQMMMC, 
     *     RCUTMM,DELFLD,ECHART,EDIPT,EQUADT,EOCTUP,
     *     EDELD,EDNUC,EDMULT,ENUMUL
#else
      DOUBLE PRECISION MMCORD, MUL0MM, MUL1MM, MUL2MM, MUL3MM,
     *                 POLMM, POLIMM, THRMM, QMPOL, THMMIT,
     *                 RQMMMC, RCUTMM,DELFLD,
     *                 ECHART,EDIPT,EQUADT,EOCTUP,
     *                 EDELD,EDNUC,EDMULT,ENUMUL
#endif
      PARAMETER ( THRMM = 1.0D-10 )

      COMMON /REQMMM/ MMCORD(3,MXMMCT), MUL0MM(MXMMCT), 
     *                MUL1MM(3,MXMMCT), MUL2MM(6,MXMMCT),
     *                MUL3MM(10,MXMMCT),
     *                POLMM(6,MXMMCT), POLIMM(MXMMCT), 
     *                QMPOL(MXCENT) , THMMIT, RQMMMC, RCUTMM,
     *                DELFLD,ECHART,EDIPT,EQUADT,EOCTUP,
     *                EDELD,EDNUC,EDMULT,ENUMUL

      COMMON /LOQMMM/ SPLDIP,CONMAT,FIXDIP,MMDAMP,MMPROP,
     *                SPLNMR,MMMAT,MMITER,MMDIIS,LCLOSE,LHFFIL,
     *                LMMNUL(MXMMCT),ZEROOC,MMREST,RELMAT,
     *                LGFILE,ZERODI,ZEROQU,ISOPOL,NOPOL,NOMB,
     *                MMTIME,NEWEXC

      COMMON /INQMMM/ MMCENT,NMULT,IPOLTP,NEXLST,
     *                EXLIST(MXEXCL,MXMMCT),ZEROAL(MXMMCT),
     *                NNZAL,IDAMP,NQMNUC,MXMMIT,MXMMDI,
     *                NMMAC,IQMMMC,NELEME,ELEME(MXMMCT),IPQMMM

C --- end of qmmm.h ---
