#if defined (SYS_CRAY) 
      REAL QDRNUC, QDREL, QDRTOT, QDREL2, QDREL3
#else
      DOUBLE PRECISION QDRNUC, QDREL, QDRTOT, QDREL2, QDREL3
#endif
      COMMON /QDRMOM/ QDRNUC(3,3), QDREL(3,3), QDRTOT(3,3),              &
     &                QDREL2(3,3), QDREL3(3,3)
