      PARAMETER ( NSYMP = 36 )
      COMMON/TRINFO/ ISP,ISQ,ISR,ISS,NBP,NBQ,NBR,NBS,NBPQ,NBRS,IRRST,
     &               NOCP,NOCQ,NOCR,NOCS,NPQ,LADX,LRUPQ,LUSPQ,LTUPQ,
     &               NOP,NOQ,NOR,NOS,LMOP,LMOQ,LMOR,LMOS,
     &               LMOP2,LMOQ2,LMOR2,LMOS2,ITP,ITQ,ITR,ITS,
     &               JMOP2,JMOQ2,JMOR2,JMOS2,LX2X3,
     &               IAD1S,IAD2S,IAD3S,IPQMX1,IPQMX2,IPQMX3
