# Chunks of the library
set(OPENRSP_HEADER_CHUNKS
    RSPPerturbation.h
    RSPOverlap.h
    RSPOneOper.h
    RSPTwoOper.h
    RSPXCFun.h
    RSPNucHamilton.h
    RSPSolver.h
    OpenRSP.h)
set(OPENRSP_C_CHUNKS
    RSPPerturbation.c
    RSPOverlap.c
    RSPOneOper.c
    RSPTwoOper.c
    RSPXCFun.c
    RSPNucHamilton.c
    RSPSolver.c
    OpenRSP.c)
set(OPENRSP_FORTRAN_CHUNKS
    RSPPertBasicTypes.F90
    RSPPerturbation.F90
    RSPOverlap.F90
    RSPOneOper.F90
    RSPTwoper.F90
    RSPXCFun.F90
    RSPNucHamilton.F90
    RSPSolver.F90
    OpenRSPFortranAdapter.c
    OpenRSP.F90)
