# Chunks of the library
set(OPENRSP_HEADER_CHUNKS
    RSPPerturbation.h
    RSPOverlap.h
    RSPOneOper.h
    RSPTwoOper.h
    RSPXCFun.h
    RSPNucHamilton.h
    RSPSolver.h
    OpenRSP.h)
set(OPENRSP_C_CHUNKS
    OpenRSPCreate.c
    OpenRSPAssemble.c
    OpenRSPWrite.c
    OpenRSPDestroy.c
    OpenRSPSetPerturbations.c
    RSPPertCreate.c
    RSPPertAssemble.c
    RSPPertWrite.c
    RSPPertGetFromTuple.c
    RSPPertGetConcatenation.c
    RSPPertDestroy.c
    OpenRSPSetOverlap.c
    RSPOverlapCreate.c
    RSPOverlapAssemble.c
    RSPOverlapWrite.c
    RSPOverlapGetMat.c
    RSPOverlapGetExp.c
    RSPOverlapDestroy.c
    OpenRSPAddOneOper.c
    RSPOneOperCreate.c
    RSPOneOperAdd.c
    RSPOneOperAssemble.c
    RSPOneOperWrite.c
    RSPOneOperGetMat.c
    RSPOneOperGetExp.c
    RSPOneOperDestroy.c
    OpenRSPAddTwoOper.c
    RSPTwoOperCreate.c
    RSPTwoOperAdd.c
    RSPTwoOperAssemble.c
    RSPTwoOperWrite.c
    RSPTwoOperGetMat.c
    RSPTwoOperGetExp.c
    RSPTwoOperDestroy.c
    OpenRSPAddXCFun.c
    RSPXCFunCreate.c
    RSPXCFunAdd.c
    RSPXCFunAssemble.c
    RSPXCFunWrite.c
    RSPXCFunGetMat.c
    RSPXCFunGetExp.c
    RSPXCFunDestroy.c
    OpenRSPSetNucHamilton.c
    RSPNucHamiltonCreate.c
    RSPNucHamiltonAssemble.c
    RSPNucHamiltonWrite.c
    RSPNucHamiltonGetContributions.c
    RSPNucHamiltonGetNumAtoms.c
    RSPNucHamiltonDestroy.c
    OpenRSPSetLinearRSPSolver.c
    RSPSolverCreate.c
    RSPSolverAssemble.c
    RSPSolverWrite.c
    RSPSolverGetLinearRSPSolution.c
    RSPSolverDestroy.c
    OpenRSPGetRSPFun.c
    OpenRSPGetResidue.c)
set(OPENRSP_FORTRAN_CHUNKS
    RSPPert.F90
    RSPOverlap.F90
    RSPOneOper.F90
    RSPTwoper.F90
    RSPXCFun.F90
    RSPNucHamilton.F90
    RSPSolver.F90
    OpenRSPFortranAdapter.c
    OpenRSP.F90)
