# Generated by notangle -ROpenRSPTestData.cmake web/UnitTesting.nw > cmake/OpenRSPTestData.cmake
include_directories(${PROJECT_BINARY_DIR})
# atomic-orbital (AO) density matrix-based response theory
set(OPENRSP_TEST_DATA ${PROJECT_BINARY_DIR}/OpenRSPTestData.h)
file(WRITE ${OPENRSP_TEST_DATA} "#if !defined(OPENRSP_TEST_DATA_H)\n")
file(APPEND ${OPENRSP_TEST_DATA} "#define OPENRSP_TEST_DATA_H\n\n")
file(APPEND ${OPENRSP_TEST_DATA} "#include \"qcmatrix.h\"\n\n")
# function of reading matrices from a dat file
file(APPEND ${OPENRSP_TEST_DATA} "extern QErrorCode OpenRSPTestReadMat(const char*,\n")
file(APPEND ${OPENRSP_TEST_DATA} "                                     const QInt,\n")
file(APPEND ${OPENRSP_TEST_DATA} "                                     const QInt,\n")
file(APPEND ${OPENRSP_TEST_DATA} "                                     QcMat*[]);\n\n")
# function of zeroing matrices
file(APPEND ${OPENRSP_TEST_DATA} "extern QErrorCode OpenRSPTestZeroMat(const QInt,\n")
file(APPEND ${OPENRSP_TEST_DATA} "                                     QcMat*[]);\n\n")
# unperturbed AO-based Fock matrix
get_filename_component(FOCK_AO_HF
                       ${LIB_OPENRSP_PATH}/tests/FockAOHF.dat
                       ABSOLUTE)
file(APPEND
     ${OPENRSP_TEST_DATA}
     "#define FOCK_AO_HF \"${FOCK_AO_HF}\"\n")
# unperturbed AO-based density matrix
get_filename_component(DENS_AO_HF
                       ${LIB_OPENRSP_PATH}/tests/DensAOHF.dat
                       ABSOLUTE)
file(APPEND
     ${OPENRSP_TEST_DATA}
     "#define DENS_AO_HF \"${DENS_AO_HF}\"\n")
# unperturbed AO-based overlap integral matrix
get_filename_component(OVERLAP_AO
                       ${LIB_OPENRSP_PATH}/tests/OverlapAO.dat
                       ABSOLUTE)
file(APPEND
     ${OPENRSP_TEST_DATA}
     "#define OVERLAP_AO \"${OVERLAP_AO}\"\n")
# unperturbed AO-based dipole length integral matrices
get_filename_component(DIPLEN_AO
                       ${LIB_OPENRSP_PATH}/tests/DipLenAO.dat
                       ABSOLUTE)
file(APPEND
     ${OPENRSP_TEST_DATA}
     "#define DIPLEN_AO \"${DIPLEN_AO}\"\n")
# two-electron integrals contracted with perturbed AO-based density matrices
# for solving polarizability at frequency as 0.072
get_filename_component(ALPHA_GMAT_AO_HF
                       ${LIB_OPENRSP_PATH}/tests/AlphaGMatAOHF.dat
                       ABSOLUTE)
file(APPEND
     ${OPENRSP_TEST_DATA}
     "#define ALPHA_GMAT_AO_HF \"${ALPHA_GMAT_AO_HF}\"\n")
# response parameters for solving polarizability at frequency as 0.072
get_filename_component(ALPHA_RSPARAM_AO_HF
                       ${LIB_OPENRSP_PATH}/tests/AlphaRSParamAOHF.dat
                       ABSOLUTE)
file(APPEND
     ${OPENRSP_TEST_DATA}
     "#define ALPHA_RSPARAM_AO_HF \"${ALPHA_RSPARAM_AO_HF}\"\n")
file(APPEND ${OPENRSP_TEST_DATA} "\n#endif\n")
