# Source codes of OpenRSP library
SET(OPENRSP_SRCS
    ${LIB_OPENRSP_PATH}/src/solver/RSPSolverCreate.c
    ${LIB_OPENRSP_PATH}/src/solver/RSPSolverAssemble.c
    ${LIB_OPENRSP_PATH}/src/solver/RSPSolverWrite.c
    ${LIB_OPENRSP_PATH}/src/solver/RSPSolverGetSolution.c
    ${LIB_OPENRSP_PATH}/src/solver/RSPSolverDestroy.c
    ${LIB_OPENRSP_PATH}/src/overlap/RSPOverlapCreate.c
    ${LIB_OPENRSP_PATH}/src/overlap/RSPOverlapAssemble.c
    ${LIB_OPENRSP_PATH}/src/overlap/RSPOverlapWrite.c
    ${LIB_OPENRSP_PATH}/src/overlap/RSPOverlapGetMat.c
    ${LIB_OPENRSP_PATH}/src/overlap/RSPOverlapGetExp.c
    ${LIB_OPENRSP_PATH}/src/overlap/RSPOverlapDestroy.c
    ${LIB_OPENRSP_PATH}/src/one_oper/RSPOneOperCreate.c
    ${LIB_OPENRSP_PATH}/src/one_oper/RSPOneOperAdd.c
    ${LIB_OPENRSP_PATH}/src/one_oper/RSPOneOperAssemble.c
    ${LIB_OPENRSP_PATH}/src/one_oper/RSPOneOperWrite.c
    ${LIB_OPENRSP_PATH}/src/one_oper/RSPOneOperGetMat.c
    ${LIB_OPENRSP_PATH}/src/one_oper/RSPOneOperGetExp.c
    ${LIB_OPENRSP_PATH}/src/one_oper/RSPOneOperDestroy.c
    ${LIB_OPENRSP_PATH}/src/two_oper/RSPTwoOperCreate.c
    ${LIB_OPENRSP_PATH}/src/two_oper/RSPTwoOperAdd.c
    ${LIB_OPENRSP_PATH}/src/two_oper/RSPTwoOperAssemble.c
    ${LIB_OPENRSP_PATH}/src/two_oper/RSPTwoOperWrite.c
    ${LIB_OPENRSP_PATH}/src/two_oper/RSPTwoOperGetMat.c
    ${LIB_OPENRSP_PATH}/src/two_oper/RSPTwoOperGetExp.c
    ${LIB_OPENRSP_PATH}/src/two_oper/RSPTwoOperDestroy.c
    ${LIB_OPENRSP_PATH}/src/nuc_contrib/RSPNucContribCreate.c
    ${LIB_OPENRSP_PATH}/src/nuc_contrib/RSPNucContribSetDipoleOrigin.c
    ${LIB_OPENRSP_PATH}/src/nuc_contrib/RSPNucContribSetGaugeOrigin.c
    ${LIB_OPENRSP_PATH}/src/nuc_contrib/RSPNucContribWrite.c
    ${LIB_OPENRSP_PATH}/src/nuc_contrib/RSPNucContribGet.c
    ${LIB_OPENRSP_PATH}/src/nuc_contrib/RSPNucContribGetNumAtoms.c
    ${LIB_OPENRSP_PATH}/src/nuc_contrib/RSPNucContribDestroy.c
    ${LIB_OPENRSP_PATH}/src/OpenRSPCreate.c
    ${LIB_OPENRSP_PATH}/src/OpenRSPSetElecEOM.c
    ${LIB_OPENRSP_PATH}/src/OpenRSPSetSolver.c
    ${LIB_OPENRSP_PATH}/src/OpenRSPSetPDBS.c
    ${LIB_OPENRSP_PATH}/src/OpenRSPAddOneOper.c
    ${LIB_OPENRSP_PATH}/src/OpenRSPAddTwoOper.c
    ${LIB_OPENRSP_PATH}/src/OpenRSPSetAtoms.c
    ${LIB_OPENRSP_PATH}/src/OpenRSPSetDipoleOrigin.c
    ${LIB_OPENRSP_PATH}/src/OpenRSPSetGaugeOrigin.c
    ${LIB_OPENRSP_PATH}/src/OpenRSPAssemble.c
    ${LIB_OPENRSP_PATH}/src/OpenRSPWrite.c
    ${LIB_OPENRSP_PATH}/src/OpenRSPGetRSPFun.c
    ${LIB_OPENRSP_PATH}/src/OpenRSPDestroy.c)
IF(OPENRSP_PERTURBATION_FREE)
    SET(OPENRSP_SRCS
        ${OPENRSP_SRCS}
        ${LIB_OPENRSP_PATH}/src/OpenRSPSetPerturbations.c)
ENDIF()
