# Source codes of C test suite
SET(OPENRSP_C_TEST_SRCS
    ${LIB_OPENRSP_PATH}/tests/c/openrsp_c_molecule.c
    ${LIB_OPENRSP_PATH}/tests/c/callback_ao_dens/openrsp_c_ao_fock.c
    ${LIB_OPENRSP_PATH}/tests/c/callback_ao_dens/openrsp_c_ao_density.c
    ${LIB_OPENRSP_PATH}/tests/c/callback_ao_dens/openrsp_c_ao_overlap.c
    ${LIB_OPENRSP_PATH}/tests/c/callback_ao_dens/openrsp_c_ao_diplen.c
    ${LIB_OPENRSP_PATH}/tests/c/callback_ao_dens/openrsp_c_ao_gmat.c
    ${LIB_OPENRSP_PATH}/tests/c/callback_ao_dens/openrsp_c_ao_alpha_rsp_param.c
    ${LIB_OPENRSP_PATH}/tests/c/callback_ao_dens/get_one_oper_exp.c
    ${LIB_OPENRSP_PATH}/tests/c/callback_ao_dens/get_one_oper_mat.c
    ${LIB_OPENRSP_PATH}/tests/c/callback_ao_dens/get_two_oper_exp.c
    ${LIB_OPENRSP_PATH}/tests/c/callback_ao_dens/get_two_oper_mat.c
    ${LIB_OPENRSP_PATH}/tests/c/callback_ao_dens/get_overlap_exp.c
    ${LIB_OPENRSP_PATH}/tests/c/callback_ao_dens/get_overlap_mat.c
    ${LIB_OPENRSP_PATH}/tests/c/callback_ao_dens/get_linear_rsp_solution.c
    ${LIB_OPENRSP_PATH}/tests/c/test_c_OpenRSP_AO.c
    ${LIB_OPENRSP_PATH}/tests/c/test_c_OpenRSP.c)
IF(OPENRSP_PERTURBATION_FREE)
    SET(OPENRSP_C_TEST_SRCS
        ${OPENRSP_C_TEST_SRCS}
        ${LIB_OPENRSP_PATH}/tests/c/callback_pert/get_pert_comp.c
        ${LIB_OPENRSP_PATH}/tests/c/callback_pert/get_pert_rank.c)
ENDIF()
